Website/Website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ajax/', include('my_site.urls', namespace='my_site')),
    path('', include('account.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Website/my_site/urls.py
from django.urls import path
from . import views
from .views import (post_like)
from my_site import views

app_name = 'my_site'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/',
         views.post_list, name='post_list_by_tag'),
    path('<int:id>/', views.post_detail, name='post_detail'),
    path('like/', views.post_like, name='like'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('search/', views.search, name='search'),
    path('contact/', views.ContactView.as_view(), name='contact'),

]

Website/my_site/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
from django.conf import settings


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=30)
    body = models.TextField()
    slug = models.SlugField(max_length=50)
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_post')
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2,
                              choices=Status.choices,
                              default=Status.DRAFT)
    image = models.ImageField(upload_to='Post')
    objects = models.Manager()
    published = PublishedManager()
    tag = TaggableManager()
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                        related_name='post_liked', blank=True)

    class Meta:
        ordering = ['-publish']

        indexes = [
            models.Index(fields=['-publish'])
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('my_site:post_detail',
                       args=[self.id])


class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created'])
        ]

    def __str__(self):
        return f"Comment by {self.name} on {self.post}."


class SearchKeyword(models.Model):
    keyword = models.CharField(max_length=50)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __unicode__(self):
        return self.keyword

Website/my_site/forms.py
from django import forms
from .models import Comment
from django.core.mail import send_mail
import logging

logger = logging.getLogger(__name__)


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']


class ContactForm(forms.Form):
    name = forms.CharField(max_length=50)
    message = forms.CharField(max_length=600, widget=forms.Textarea)

    def send_mail(self):
        logger.info("Sending email...")
        message = "From: {0}\n{1}".format(
            self.cleaned_data["name"],
            self.cleaned_data["message"],
        )
        send_mail(
            "Site message",
            message,
            "admin@admin.com",
            ["admin@admin.com"],
            fail_silently=False,
        )

Website/my_site/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import EmailPostForm, CommentForm, ContactForm
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
from django.views.generic.edit import FormView
from my_site import forms
from django.db.models import Q, Count
from taggit.models import Tag
from django.contrib.auth.decorators import login_required


def post_list(request, tag_slug=None):
    post_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
    paginator = Paginator(post_list, 3)
    page_number = request.GET.get('page')

    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request,
                  'my_site/post/list.html',
                  {'posts': posts,
                   'tag': tag})


def post_detail(request, id):
    post = get_object_or_404(Post, id=id, status=Post.Status.PUBLISHED)
    comments = post.comments.filter(active=True)
    form = CommentForm()
    post_tag_ids = post.tag.values_list('id', flat=True)
    similar_posts = Post.published.filter(tag__in=post_tag_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tag=Count('tag')).order_by('-same_tag', '-publish')[:4]
    return render(request,
                  'my_site/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'form': form,
                   'similar_posts': similar_posts})


@login_required
@require_POST
def post_like(request):
    post_id = request.POST.get('id')
    action = request.POST.get('action')
    if post_id and action:
        try:
            post = Post.objects.get(id=post_id)
            if action == 'like':
                post.users_like.add(request.user)
            else:
                post.users_like.remove(request.user)
            return JsonResponse({'status': 'ok'})
        except Post.DoesNotExist:
            pass
    return JsonResponse({'status': 'error'})


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False

    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(
                post.get_absolute_url()
            )
            subject = f"{cd['name']} recommends you read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n {cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'admin@admin.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request,
                  'my_site/post/share.html',
                  {"post": post,
                   'form': form})


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    return render(request, 'my_site/post/comment.html',
                  {'post': post,
                   'form': form,
                   'comment': comment})


def search(request):
    query = request.GET.get('q', '')
    keyword_results = results = []
    if query:
        keyword_results = Post.objects.filter(searchkeyword__keyword__in=query.split()).distinct()
        if keyword_results.count() == 1:
            return HttpResponseRedirect(keyword_results[0].get_absolute_url())
        results = Post.objects.filter(Q(title__icontains=query) | Q(body__icontains=query))
    return render(request, 'my_site/search.html',
                  {'query': query,
                   'keyword_results': keyword_results,
                   'results': results})


class ContactView(FormView):
    template_name = "my_site/post/contact.html"
    form_class = forms.ContactForm
    success_url = "/ajax/contact"

    def form_valid(self, form):
        form.send_mail()
        return super().form_valid(form)

Website/my_site/templates/my_site/base.html
{% load my_site_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static '/my_site/main.css/' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="">My Webapp</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="mynavbar">
      <ul class="navbar-nav me-auto">
          <li class="nav-item">
          <a class="nav-link" href="{% url 'my_site:post_list' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'my_site:contact' %}">Contact me</a>
        </li>
      </ul>
        {% include "my_site/search.html" %}
    </div>
  </div>
    <div id="header">
        {% if request.user.is_authenticated %}
       <ul class="menu">
        <li {% if section == "dashboard" %} class="selected"{% endif %}>
            <a href="{% url 'dashboard' %}">My dashboard</a>
        </li>
       </ul>
        {% endif %}
        <span class="user">
            {% if request.user.is_authenticated %}
                Hello {{ request.user.first_name|default:request.user.username }}<br>
                <a href="{% url 'logout' %}">Logout</a>
            {% else %}
                <a href="{% url 'login' %}">Login</a>
            {% endif %}
        </span>
    </div>
</nav>
<div id="content">
    {% block content %}
    {% endblock %}
</div>
<div id="sidebar">
    <h2>My blog</h2>
    <p>
        I've written {% total_posts %} posts so far.
    </p>
    <h3>Latest posts</h3>
    {% show_latest_posts 3 %}
    <h3>Most commented posts</h3>
    {% get_most_commented_posts as most_commented_posts %}
    <ul>
        {% for post in most_commented_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
        {% endfor %}
    </ul>
</div>
<script src="//cdn.jsdelivr.net/npm/js-cookie@3.0.1/dist/js.cookie.min.js"></
script>
 <script>
 const csrftoken = Cookies.get('csrftoken');
 document.addEventListener('DOMContentLoaded', (event) => {
 // DOM loaded
 {% block domready %}
 {% endblock %}
 })
 </script>

</body>
</html>

Website/my_site/templates/my_site/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}
        </span>
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>

Website/my_site/templates/my_site/search.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Search</title>
    <link href="{% static '/my_site/main.css/' %}" rel="stylesheet">
</head>
<body>
<form method="get" action="/ajax/search/">
    <h3><label for="id_q"></label>
    <input type="text" name="q" id="id_q" value="{{ query }}" placeholder="Search">
     <input type="submit" value="Search"></h3>
</form>
<br><br><br><br><br><br>
{% if keyword_results or results %}
 <p>You searched for "{{ query }}".</p>
 {% if keyword_results %}
 <p>Recommended pages:</p>
 <ul>
 {% for post in keyword_results %}
 <li>
  <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
 </li>
 {% endfor %}
 </ul>
 {% endif %}
 {% if results %}
 <p>Search results:</p>
 <ul>
 {% for post in results %}
 <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
 {% endfor %}
 </ul>
 {% endif %}
 {% endif %}
 {% if query and not keyword_results and not results %}
 <p>No results found.</p>
 {% endif %}

</body>
</html>