Website/Website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ajax/', include('my_site.urls', namespace='my_site')),
    path('', include('account.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Website/my_site/urls.py
from django.urls import path
from . import views
from .views import (post_like)
from my_site import views

app_name = 'my_site'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/',
         views.post_list, name='post_list_by_tag'),
    path('<int:id>/', views.post_detail, name='post_detail'),
    path('like/', views.post_like, name='like'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('search/', views.search, name='search'),
    path('contact/', views.ContactView.as_view(), name='contact'),

]

Website/my_site/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
from django.conf import settings


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=30)
    body = models.TextField()
    slug = models.SlugField(max_length=50)
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_post')
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2,
                              choices=Status.choices,
                              default=Status.DRAFT)
    image = models.ImageField(upload_to='Post')
    objects = models.Manager()
    published = PublishedManager()
    tag = TaggableManager()
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                        related_name='post_liked', blank=True)

    class Meta:
        ordering = ['-publish']

        indexes = [
            models.Index(fields=['-publish'])
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('my_site:post_detail',
                       args=[self.id])


class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created'])
        ]

    def __str__(self):
        return f"Comment by {self.name} on {self.post}."


class SearchKeyword(models.Model):
    keyword = models.CharField(max_length=50)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __unicode__(self):
        return self.keyword

Website/my_site/forms.py
from django import forms
from .models import Comment
from django.core.mail import send_mail
import logging

logger = logging.getLogger(__name__)


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']


class ContactForm(forms.Form):
    name = forms.CharField(max_length=50)
    message = forms.CharField(max_length=600, widget=forms.Textarea)

    def send_mail(self):
        logger.info("Sending email...")
        message = "From: {0}\n{1}".format(
            self.cleaned_data["name"],
            self.cleaned_data["message"],
        )
        send_mail(
            "Site message",
            message,
            "admin@admin.com",
            ["admin@admin.com"],
            fail_silently=False,
        )

Website/my_site/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import EmailPostForm, CommentForm, ContactForm
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
from django.views.generic.edit import FormView
from my_site import forms
from django.db.models import Q, Count
from taggit.models import Tag
from django.contrib.auth.decorators import login_required


def post_list(request, tag_slug=None):
    post_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
    paginator = Paginator(post_list, 3)
    page_number = request.GET.get('page')

    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request,
                  'my_site/post/list.html',
                  {'posts': posts,
                   'tag': tag})


def post_detail(request, id):
    post = get_object_or_404(Post, id=id, status=Post.Status.PUBLISHED)
    comments = post.comments.filter(active=True)
    form = CommentForm()
    post_tag_ids = post.tag.values_list('id', flat=True)
    similar_posts = Post.published.filter(tag__in=post_tag_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tag=Count('tag')).order_by('-same_tag', '-publish')[:4]
    return render(request,
                  'my_site/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'form': form,
                   'similar_posts': similar_posts})


@login_required
@require_POST
def post_like(request):
    post_id = request.POST.get('id')
    action = request.POST.get('action')
    if post_id and action:
        try:
            post = Post.objects.get(id=post_id)
            if action == 'like':
                post.users_like.add(request.user)
            else:
                post.users_like.remove(request.user)
            return JsonResponse({'status': 'ok'})
        except Post.DoesNotExist:
            pass
    return JsonResponse({'status': 'error'})


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False

    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(
                post.get_absolute_url()
            )
            subject = f"{cd['name']} recommends you read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n {cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'admin@admin.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request,
                  'my_site/post/share.html',
                  {"post": post,
                   'form': form})


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    return render(request, 'my_site/post/comment.html',
                  {'post': post,
                   'form': form,
                   'comment': comment})


def search(request):
    query = request.GET.get('q', '')
    keyword_results = results = []
    if query:
        keyword_results = Post.objects.filter(searchkeyword__keyword__in=query.split()).distinct()
        if keyword_results.count() == 1:
            return HttpResponseRedirect(keyword_results[0].get_absolute_url())
        results = Post.objects.filter(Q(title__icontains=query) | Q(body__icontains=query))
    return render(request, 'my_site/search.html',
                  {'query': query,
                   'keyword_results': keyword_results,
                   'results': results})


class ContactView(FormView):
    template_name = "my_site/post/contact.html"
    form_class = forms.ContactForm
    success_url = "/ajax/contact"

    def form_valid(self, form):
        form.send_mail()
        return super().form_valid(form)

Website/my_site/templates/my_site/post/comment.html
{% extends "my_site/base.html" %}

{% block title %}Add a comment {% endblock %}

{% block content %}
{% if comment %}
<h2>Your comment has been added.</h2>
<p><a href="{{ post.get_absolute_url }}">Back to post</a> </p>
{% else %}
{% include "my_site/post/includes/comment_form.html" %}
{% endif %}
{% endblock %}

Website/my_site/templates/my_site/post/contact.html
{% extends "my_site/base.html" %}

{% block title %}Contact me{% endblock %}

{% block content %}
<h2>Contact me</h2>
<p>Please fill the form below to contact me.</p>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary" style="float:left;">Submit</button>
</form>
{% endblock %}

Website/my_site/templates/my_site/post/detail.html
{% extends "my_site/base.html" %}
{% load my_site_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
{{ post.title }}
<p class="date">
    Published {{ post.publish }} by {{ post.author }}
</p>
<p>
    {{ post.body|markdown }}
</p>

<img src="{{ post.image.url }}" height="200" width="200" alt="no pic yet">
<p>
    <a href="{% url 'my_site:post_share' post.id %}">Share this post</a>
</p><br><br>
{% with total_likes=post.users_like.count users_like=post.users_like.all %}
    <div>
       <div>
        <span class="count">
          <span class="total">{{ total_likes }}</span>
          like{{ total_likes|pluralize }}
        </span>
        <a href="#" data-id="{{ post.id }}" data-action="{% if request.user in users_like %}un{% endif %}like"
           class="like button">
          {% if request.user not in users_like %}
            Like
          {% else %}
            Unlike
          {% endif %}
        </a>
      </div>
    </div>
{% endwith %}
<h2>Similar posts by tags</h2>
{% for post in similar_posts %}
<p>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
</p>

{% empty %}
There are no similar posts yet.
{% endfor %}

{% with comments.count as total_comments %}
<h2>
    {{ total_comments }} comment {{ total_comments|pluralize }}
</h2>
{% endwith %}
{% for comment in comments %}
<div class="comment">
    <p class="info">
        Comment {{ forloop.counter }} by {{ comment.name }}: <br>
    </p>
    {{ comment.body|linebreaks }}
</div>
{% empty %}
<p>There are no comments yet.</p>
{% endfor %}
{% include "my_site/post/includes/comment_form.html" %}
{% endblock %}


{% block domready %}
const url = '{% url "my_site:like" %}';
var options = {
  method: 'POST',
  headers: {'X-CSRFToken': csrftoken},
  mode: 'same-origin'
}

document.querySelector('a.like')
        .addEventListener('click', function(e){
  e.preventDefault();
  var likeButton = this;

  var formData = new FormData();
  formData.append('id', likeButton.dataset.id);
  formData.append('action', likeButton.dataset.action);
  options['body'] = formData;

  fetch(url, options)
  .then(response => response.json())
  .then(data => {
    if (data['status'] === 'ok')
    {
      var previousAction = likeButton.dataset.action;

      var action = previousAction === 'like' ? 'unlike' : 'like';
      likeButton.dataset.action = action;
      likeButton.innerHTML = action;

      var likeCount = document.querySelector('span.count .total');
      var totalLikes = parseInt(likeCount.innerHTML);
          likeCount.innerHTML = previousAction === 'like' ? totalLikes + 1 : totalLikes - 1;
    }
  })
});
{% endblock %}

Website/my_site/templates/my_site/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
    <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
    {% endfor %}
</ul>

Website/my_site/templates/my_site/post/list.html
{% extends "my_site/base.html" %}
{% load my_site_tags %}

{% block title %}Welcome{% endblock %}

{% block content %}

{% if tag %}
<h2>Post tagged with "{{ tag.name }}" </h2>
{% endif %}

{% for post in posts %}
<h2>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
</h2>
<p class="tags">Tags:
    {% for tag in post.tag.all %}
    <a href="{% url 'my_site:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
    {% if not forloop.last %}, {% endif %}
    {% endfor %}
</p>
<p class="date">
    Published {{ post.publish }} by {{ post.author }}
</p>
{{ post.body|markdown|truncatewords_html:10 }}

{% endfor %}
{% include "my_site/pagination.html" with page=posts %}
{% endblock %}

Website/my_site/templates/my_site/post/share.html
{% extends "my_site/base.html" %}

{% block title %}Share post{% endblock %}

{% block content %}
{% if sent %}
<h1>E-mail sent successfully</h1>
<p>
    "{{ post.title }}" was sent successfully to {{ form.cleaned_data.to }}.
</p>
{% else %}
<h1>Share "{{ post.title }}" by e-mail.</h1>
<form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Send e-mail">
</form>
{% endif %}
{% endblock %}